#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

echo -e "Making pre-commit requirements.txt"

pipreqs . 


if [ $? = 0 ]; then
	echo "Requirements.txt created succesfully"
else
	echo "Requirements.txt not created succesfully"
	echo "Cancelling commit"
	exit 1
fi
